import React, { Suspense } from 'react';
import Posts from '../component/Post/Posts';
import Loading from './loading';

// Page metadata
export const metadata = {
  title: 'Posts',
  description: 'Generated by create next app',
};

const PostsPage = () => {
  // Fetch posts data from API
  const postPromise = fetch('https://jsonplaceholder.typicode.com/posts').then(
    (res) => res.json()
  );

  return (
    <div>
      {/* Suspense shows loading UI while posts are loading */}
      <Suspense fallback={<Loading />}>
        
        {/* Pass fetched post promise to Posts component */}
        <Posts postPromise={postPromise} />
      </Suspense>
    </div>
  );
};

export default PostsPage;