import React, { Suspense } from 'react';
import Posts from '../component/Post/Posts';
import Loading from './loading';

export const metadata = {
  title: "Posts",
  description: "Generated by create next app",
};

const PostsPage = () => {

    const postPromise = fetch("https://jsonplaceholder.typicode.com/posts")
    .then(res => res.json());

    return (
        <div>
            <Suspense fallback={<Loading></Loading>}>
                <Posts postPromise={postPromise} />
            </Suspense>        
        </div>
    );
};

export default PostsPage;